name: Enforce No Squash Merging

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-merge-method:
    runs-on: ubuntu-latest
    steps:
      - name: Check if squash merge is disabled
        run: |
          if [ "${{ github.event.pull_request.merge_commit_sha }}" == "" ]; then
            echo "Squash merging is not allowed. Please use 'Create a merge commit' or 'Rebase and merge'."
            exit 1
          fi
