name: Update-link

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  replace-link:
    if: endsWith(github.base_ref, 'stand/release') == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Add build link to body
        id: body_with_build_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_BUILD%'
          string: ${{ github.event.pull_request.body }}
          replace-with: ${{ github.head_ref }}

      - name: Prepare stand branch name
        id: prepared_stand_branch_name
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '(feature|fix|hotfix)\/'
          string: ${{ github.head_ref }}
          replace-with: ''

      - name: Format stand branch for links
        id: formatted_stand_branch
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '\/'
          string: ${{ steps.prepared_stand_branch_name.outputs.replaced }}
          replace-with: '-'

      - name: Add stand link to body
        id: body_with_stand_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_STAND%'
          string: ${{ steps.body_with_build_link.outputs.replaced }}
          replace-with: ${{ steps.formatted_stand_branch.outputs.replaced }}

      - name: PR body replace
        uses: AsasInnab/pr-body-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.body_with_stand_link.outputs.replaced }}
