name: Update PR Description

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  replace-link:
    if: endsWith(github.base_ref, 'stand/release') == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Define string replacements
        run: |
          echo "BRANCH_BUILD=${{ github.head_ref }}" >> $GITHUB_ENV
          STAND_BRANCH=$(echo "${{ github.head_ref }}" | sed 's/\//-/g')
          echo "STAND_BRANCH=$STAND_BRANCH" >> $GITHUB_ENV
          JIRA_STAND=$(echo "${{ github.head_ref }}" | sed 's/^\(feature\|fix\|hotfix\)\///g')
          echo "JIRA_STAND=$JIRA_STAND" >> $GITHUB_ENV
          JIRA_BRANCH=$(echo "${{ github.head_ref }}" | sed 's/^\(feature\|fix\|hotfix\)\/B2CFRONT-//g')
          echo "JIRA_BRANCH=$JIRA_BRANCH" >> $GITHUB_ENV

      - name: Add build link to body
        id: body_with_build_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_BUILD%'
          string: ${{ github.event.pull_request.body }}
          replace-with: ${{ env.BRANCH_BUILD }}

      - name: Add stand link to body
        id: body_with_stand_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_STAND%'
          string: ${{ steps.body_with_build_link.outputs.replaced }}
          replace-with: ${{ env.JIRA_STAND }}

      - name: Add jira link to body
        id: body_with_jira_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%JIRA%'
          string: ${{ steps.body_with_stand_link.outputs.replaced }}
          replace-with: ${{ env.JIRA_BRANCH }}

      - name: PR body replace
        uses: AsasInnab/pr-body-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.body_with_jira_link.outputs.replaced }}
