name: Update PR Description

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  replace-link:
    if: startsWith(github.base_ref, 'stand/release')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Add build link to body
        id: body_with_build_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_BUILD%'
          string: ${{ github.event.pull_request.body }}
          replace-with: ${{ github.head_ref }}

      - name: Prepare stand branch name
        id: prepared_stand_branch_name
        run: echo "${{ github.head_ref }}" | sed 's/\//-/g' > stand_branch_name.txt

      - name: Get stand branch name
        id: get_stand_branch_name
        run: echo "::set-output name=stand_name::$(cat stand_branch_name.txt)"

      - name: Add stand link to body
        id: body_with_stand_link
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_STAND%'
          string: ${{ steps.body_with_build_link.outputs.replaced }}
          replace-with: ${{ steps.get_stand_branch_name.outputs.stand_name }}

      - name: PR body replace
        uses: AsasInnab/pr-body-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.body_with_stand_link.outputs.replaced }}
