name: Update PR Description

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  replace-link:
    if: endsWith(github.base_ref, 'stand/release') == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Define and set string replacements
        run: |
          echo "BRANCH_BUILD=${{ github.head_ref }}" >> $GITHUB_ENV
          STAND_BRANCH=$(echo "${{ github.head_ref }}" | sed 's/^\(feature\|fix\|hotfix\)\///g')
          echo "STAND_BRANCH=$STAND_BRANCH" >> $GITHUB_ENV
          JIRA_TASK_NUMBER=$(echo "$STAND_BRANCH" | sed 's/^B2CFRONT-//g')
          echo "JIRA_TASK_NUMBER=$JIRA_TASK_NUMBER" >> $GITHUB_ENV

      - name: Replace %BRANCH_BUILD% in PR body
        id: update_body_build
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_BUILD%'
          string: ${{ github.event.pull_request.body }}
          replace-with: ${{ env.BRANCH_BUILD }}

      - name: Replace %BRANCH_STAND% in PR body
        id: update_body_stand
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%BRANCH_STAND%'
          string: ${{ steps.update_body_build.outputs.replaced }}
          replace-with: ${{ env.STAND_BRANCH }}

      - name: Replace %JIRA% in PR body
        id: update_body_jira
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '%JIRA%'
          string: ${{ steps.update_body_stand.outputs.replaced }}
          replace-with: ${{ env.JIRA_TASK_NUMBER }}

      - name: Update PR body with final result
        uses: AsasInnab/pr-body-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.update_body_jira.outputs.replaced }}
